my_string = input('Напишите вашу фамилию и имя - ')
print("В данной строке находится",len(my_string), "символа")
print('ВЕРХНИЙ РЕГИСТ -',my_string.upper())
print('нижний регистр -',my_string.lower())
print('Без пробелов -',my_string.replace(' ', ''))
print('Первая буква -',my_string[0])
print('Последняя буква -',my_string[-1])